// https://nuxt.com/docs/api/configuration/nuxt-config
const APP_NAME = "بازی جاسوس";
const DESCRIPTION = "بازی گروهی جاسوس روی یک گوشی: کلمه را پیدا کن، جاسوس را لو بده!";
const THEME_COLOR = "#891515";

export default defineNuxtConfig({
  // The game runs fully on the client (offline, single device), so SSR adds nothing.
  ssr: false,
  app: {
    // Styles live in assets/css/base.css; durations come from motion tokens (0 for reduced motion).
    pageTransition: { name: "page", mode: "out-in" },
    head: {
      title: APP_NAME,
      htmlAttrs: { lang: "fa", dir: "rtl" },
      meta: [
        { charset: "utf-8" },
        // viewport-fit=cover enables env(safe-area-inset-*) on notched phones.
        {
          name: "viewport",
          content: "width=device-width, initial-scale=1, viewport-fit=cover",
        },
        { name: "description", content: DESCRIPTION },
        { name: "theme-color", content: THEME_COLOR },
        { name: "apple-mobile-web-app-capable", content: "yes" },
        { name: "apple-mobile-web-app-status-bar-style", content: "black-translucent" },
      ],
      link: [
        // In the static HTML (not injected at runtime) so browsers detect the app as installable.
        { rel: "manifest", href: "/manifest.webmanifest" },
        { rel: "icon", href: "/favicon.ico", sizes: "32x32" },
        { rel: "icon", href: "/icon.svg", type: "image/svg+xml" },
        { rel: "apple-touch-icon", href: "/apple-touch-icon-180x180.png" },
      ],
    },
  },
  modules: ["@pinia/nuxt", "@nuxt/eslint", "@vite-pwa/nuxt"],
  css: ["~/assets/css/tokens.css", "~/assets/css/base.css"],
  // Components are auto-imported by file name (AppButton, PlayerCard, ...) regardless of folder.
  components: [{ path: "~/components", pathPrefix: false }],
  typescript: {
    strict: true,
  },
  // Installable, offline-capable app. Icons are generated by `npm run generate-icons`.
  pwa: {
    registerType: "autoUpdate",
    manifest: {
      name: APP_NAME,
      short_name: "جاسوس",
      description: DESCRIPTION,
      lang: "fa",
      dir: "rtl",
      start_url: "/",
      display: "standalone",
      orientation: "portrait",
      theme_color: THEME_COLOR,
      background_color: THEME_COLOR,
      icons: [
        { src: "pwa-64x64.png", sizes: "64x64", type: "image/png" },
        { src: "pwa-192x192.png", sizes: "192x192", type: "image/png" },
        { src: "pwa-512x512.png", sizes: "512x512", type: "image/png" },
        {
          src: "maskable-icon-512x512.png",
          sizes: "512x512",
          type: "image/png",
          purpose: "maskable",
        },
      ],
    },
    workbox: {
      // Cache the whole app so it works without a connection after the first visit.
      globPatterns: ["**/*.{js,css,html,svg,png,ico,woff2}"],
      // Error pages from `nuxt generate`: hosts may answer them with a 404 status, which makes
      // the whole precache (and so offline play) fail. The app renders its own error page anyway.
      globIgnores: ["**/404.html", "**/200.html"],
      navigateFallback: "/",
    },
    client: { installPrompt: false },
  },
  compatibilityDate: "2024-04-03",
  devtools: { enabled: false },
  $production: {
    hooks: {
      // The design-system playground under /dev only exists during development.
      "pages:extend"(pages) {
        const devPages = pages.filter((page) => page.path.startsWith("/dev"));
        devPages.forEach((page) => pages.splice(pages.indexOf(page), 1));
      },
    },
  },
});
